Program Bonuses;

{This program prompts the user to input the sales representative’s number terminated by 0 and their income generated, calculates and prints the bonus and salary plus bonus}
{Created by : Arianna St.John}
{Date : 10/22/2022}

Var
    Number : Integer;
    IncomeGen, Bonus, SalaryPlus : Real;
Begin 
    Write ('Enter the income generated by the sales representatives: ');
    Readln (IncomeGen);
    Write ('Enter the sales representative''s number: ');
    Readln (Number);
    While Number <> 0 
    Do
    Begin
        If IncomeGen > 5000 
        Then
        Begin
            Bonus := IncomeGen * 10 / 100;
        End
        Else
        Begin
            Bonus := 0;
        End;
        SalaryPlus := Bonus + 4000;
        Writeln ('The bonus awarded is: ', Bonus : 0 : 2);
        Writeln ('The salary plus bonus is: ', SalaryPlus : 0 : 2);
        Write ('Enter the income generated by the sales representatives: ');
        Readln (IncomeGen);
        Write ('Enter the sales representative''s number: ');
        Readln (Number);
    End; 
End.
